InmemDb/Models/Dish.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InmemDb.Models
{
    public class Dish
    {
        public int DishId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public List<DishIngredient> DishIngredients { get; set; }
    }
}

InmemDb/Controllers/DishController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InmemDb.Data;
using InmemDb.Models;
using Microsoft.AspNetCore.Http;
using InmemDb.Services;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace InmemDb.Controllers
{
    public class DishController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DishController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dishes
        public async Task<IActionResult> Index(int id)
        {
            var catlist = await _context.Category.ToListAsync();

            var dishes = await _context.Dishes
                .Include(x => x.DishIngredients)
                .ToListAsync();

            return View("Index", dishes);
        }

        // GET: Dishes/Create
        public async Task<IActionResult> Create(int dishId)
        {
            var model = new NewDishVM
            {
                Categories = await _context.Category.ToListAsync(),
                Ingredients = await _context.Ingredients.ToListAsync()
            };
            return View("Edit", model);
        }

        public IActionResult Edit(int? id)
        {
            var model = new NewDishVM()
            {
                Dish = _context.Dishes.FirstOrDefault(x => x.DishId == id),
                Ingredients = _context.Ingredients.ToList(),
                IngredientIds = _context.DishIngredients
                .Include(x => x.Dish)
                .Include(x => x.Ingredient)
                .Where(s => s.DishId == id)
                .Select(i => i.IngredientId).ToList(),
                Categories = _context.Category.ToList()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(NewDishVM newDish)
        {
            if (newDish.Dish.DishId == 0)
            {
                var dish = new Dish
                {
                    Name = newDish.Dish.Name,
                    CategoryId = newDish.Dish.CategoryId,
                    Price = newDish.Dish.Price
                };

                var ingredients = _context.Ingredients.Where(x => newDish.IngredientIds.Contains(x.IngredientId)).ToList();

                _context.Dishes.Add(dish);

                foreach (var item in ingredients)
                {
                    var dishIngredient = new DishIngredient
                    {
                        Dish = dish,
                        Ingredient = item
                    };
                    _context.DishIngredients.Add(dishIngredient);
                }


                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                var dish = _context.Dishes
                    .Include(x => x.DishIngredients)
                    .ThenInclude(i => i.Ingredient)
                    .SingleOrDefault(s => s.DishId == newDish.Dish.DishId);


                var ingredientsToRemove = _context.DishIngredients
                .Where(x => x.DishId == newDish.Dish.DishId).ToList();

                foreach (var item in ingredientsToRemove)
                {
                    dish.DishIngredients.Remove(item);
                }
                _context.SaveChanges();
                var dishIngredients = _context.Ingredients.Where(x => newDish.IngredientIds.Contains(x.IngredientId)).ToList();

                var listOfDishIngredient = new List<DishIngredient>();

                foreach (var item in dishIngredients)
                {
                    var x = new DishIngredient
                    {
                        Dish = dish,
                        DishId = dish.DishId,
                        Ingredient = item,
                        IngredientId = item.IngredientId
                    };
                    _context.DishIngredients.Add(x);
                }

                dish.Name = newDish.Dish.Name;
                dish.Price = newDish.Dish.Price;

                _context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        // GET: Dishes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = await _context.Dishes
                .SingleOrDefaultAsync(m => m.DishId == id);
            if (dish == null)
            {
                return NotFound();
            }

            return View(dish);
        }

        // POST: Dishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dish = await _context.Dishes.SingleOrDefaultAsync(m => m.DishId == id);
            _context.Dishes.Remove(dish);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DishExists(int id)
        {
            return _context.Dishes.Any(e => e.DishId == id);
        }
    }
}

InmemDb/Views/Dish/Delete.cshtml
@model InmemDb.Models.Dish

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Dish</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DishId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InmemDb/Views/Dish/Edit.cshtml
@model NewDishVM
@{
    ViewData["Title"] = "Edit";
}

<form asp-controller="Dish" asp-action="Edit" method="post">
    <input asp-for="@Model.Dish.DishId" type="hidden" />
    <div class="row">
        <input class="validate" asp-for="@Model.Dish.Name">
        <label>Dish</label>
    </div>
    <div class="row">
        <input class="validate" asp-for="@Model.Dish.Price">
        <label>Price</label>
    </div>
    <div class="row">
        <select asp-for="@Model.IngredientIds" id="IngredientsList" style="width:200px;height:300px;">
            @foreach (var item in Model.Ingredients)
            {
                <option value="@item.IngredientId">@item.Name</option>
            }
        </select>
    </div>
    <div class="form-group">
        <select asp-for="@Model.Dish.CategoryId" id="CatagoriesList">
            @foreach (var item in Model.Categories)
            {
                <option value="@item.CategoryId">@item.Name</option>
            }
        </select>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>

</form>

InmemDb/Views/Dish/Index.cshtml
@model List<Dish>
@inject InmemDb.Services.IIngredientService _ingredientService
<link href="~/css/HomeIndexTable.css" rel="stylesheet" />

@if (User.IsInRole("Admin"))
{
    <h2><a asp-action="Edit" asp-controller="Dish">Create new dish</a></h2>
}


<div class="col-lg-8">
    <table>
        <tr>
            <td style="font-size:30px;background-color:green;color:white;">Dishes</td>
        </tr>
        @foreach (var item in Model)
    {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>

                        
                <td style="font-size:10px;">
                    @foreach (var ingredient in await _ingredientService.GetIngredients(item.DishId))
                    {
                        @ingredient.Name<br />
                    }
                </td>

                <td>@Html.DisplayFor(modelItem => item.Price)</td>
                <td>
                    <a class="btn btn-primary"
                       asp-controller="ShoppingCart"
                       asp-action="AddDishToCart"
                       asp-route-dishId=@item.DishId
                       data-ajax="true"
                       data-ajax-method="GET"
                       data-ajax-mode="replace"
                       data-ajax-update="#CartPartial"
                       >
                        Add
                    </a>
                </td>
                @if (User.IsInRole("Admin"))
        {
                    <td>
                        <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.DishId">
                            <span class="glyphicon glyphicon-edit">Edit</span>
                        </a>
                    </td>
                    <td>
                        <a class="btn btn-warning" asp-action="Delete" asp-route-id="@item.DishId">
                            <span class="glyphicon glyphicon-alert">Delete</span>
                        </a>
                    </td>
                }
            </tr>
        }
    </table>
</div>


<div class="col-lg-4" id="CartPartial">
</div>